CREATE TABLE IF NOT EXISTS usuarios(
	id SERIAL NOT NULL,
	nome VARCHAR(200),
	email VARCHAR(200),
	senha VARCHAR(50),
	sexo VARCHAR(20),
	data_nascimento VARCHAR(10),
	telefone VARCHAR(15),
	usertoken VARCHAR(100) NOT NULL UNIQUE,
	tipo VARCHAR(20),
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS usuarios_pendentes(
	id SERIAL NOT NULL,
	nome VARCHAR(200),
	email VARCHAR(200),
	senha VARCHAR(50),
	sexo VARCHAR(20),
	data_nascimento VARCHAR(10),
	telefone VARCHAR(15),
	usertoken VARCHAR(100) NOT NULL UNIQUE,
	tipo VARCHAR(20),
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS foto_perfil (
  id SERIAL NOT NULL,
  user_id INT,
  usertoken VARCHAR(100),
  img_json JSONB
);

CREATE TABLE IF NOT EXISTS publicacao(
	id SERIAL NOT NULL,
	conteudo VARCHAR NOT NULL,
	usertoken VARCHAR(100) NOT NULL,
	visivel BOOLEAN NOT NULL DEFAULT TRUE,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS likes(
	id SERIAL NOT NULL,
	id_pub VARCHAR NOT NULL,
	usertoken VARCHAR(100) NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comentarios(
	id SERIAL NOT NULL,
	id_pub VARCHAR NOT NULL,
    conteudo VARCHAR NOT NULL,
	usertoken VARCHAR(100) NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS denuncias(
	id SERIAL NOT NULL,
	id_pub VARCHAR NOT NULL,
    conteudo VARCHAR NOT NULL,
	usertoken VARCHAR(100) NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS amigos(
	id SERIAL NOT NULL,
	pessoa_id INTEGER NOT NULL,
	pessoa1_id INTEGER NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS solicitacao_amigo(
	id SERIAL NOT NULL,
	de_id INTEGER NOT NULL,
	para_id INTEGER NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS perfis(
	id SERIAL NOT NULL,
	usertoken VARCHAR NOT NULL,
	tags VARCHAR,
	cidade VARCHAR,
	sobre VARCHAR DEFAULT 'Sem resumo cadastrado.',
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS grupo(
	id SERIAL NOT NULL,
	titulo VARCHAR NOT NULL,
	criador_id INTEGER NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS membros_grupo(
	id SERIAL NOT NULL,
	id_grupo INTEGER NOT NULL,
	id_membro INTEGER NOT NULL,
	data_adicao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS mensagem_grupo(
	id SERIAL NOT NULL,
	conteudo VARCHAR NOT NULL,
	autor INTEGER NOT NULL,
	grupo_id INTEGER NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS mensagem_privada(
	id SERIAL NOT NULL,
	conteudo VARCHAR NOT NULL,
	autor INTEGER NOT NULL,
	privado_id INTEGER NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS privado(
	id SERIAL NOT NULL,
	pessoa1_id INTEGER NOT NULL,
	pessoa2_id INTEGER NOT NULL,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);